global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "inference-api"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["inference-api:8000"]
        labels:
          service: "clinical-prediction-api"

  # When running outside Docker, use localhost
  # - targets: ['localhost:8000']

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
